### ISSUE TITLE
Coalescence for abstract layers in abstract housing lyphs?

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-viewer#103]
In some models, abstract layers of abstract lyphs are used as housing lyphs, e.g., in 
https://docs.google.com/spreadsheets/d/1eaMApU2QDzpAJJ-vug-4Hxd3_zQMqQDjygAjX2eRM38/edit#gid=1006273879

This results in a coalescence generation warning:
No lyph instances found for abstract coalescence
{"id":"S42_cls_ac-l42_b_lyph_4","class":"Coalescence","generated":true,"topology":"EMBEDDING","lyphs":["S42","ac-l42_b_lyph_4"]}
[[],["ac-l42_b_lyph_4"]]

The responsible code contains the following TODO comments:
//TODO find derived lyph instances recursively?
//TODO do not define coalescences for layers of abstract lyphs?

We should discuss whether using abstrac layers as housing lyphs should be allowed, and if it is allowed, extend coalescence generation to recursively expand to all instances of abstract layers.

**Comment by tgbugs** [comment]
It seems the issue here is when using layers, internalLyphs, and internalLyphsInLayers. The list of lyphs in for the layers are usually present in the same sheet and so using internalLyphsInLayers adds an unneeded level of indirection that is hard for a human to follow/debug. It would be better to specify internalLyphs on the lyphs that are in the layers column. These two approaches are equivalent (`internalLyphs -> layers` and `layers -> internalLyphs + internalLyphsInLayers`) but for now it seems that there is no reason to use the 2nd form. There might be a case where the specification of the layer is somehow separate, inaccessible, generated, etc. in which case it would make sense to allow the 2nd pattern but at the moment there doesn't seem to be one.

**Comment by albatros13** [comment]
No action required
