### ISSUE TITLE
Link group templates, e.g., chains, to nested groups

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-viewer#11]
The ApiNATOMY schema allows users to define group templates within nested groups. Users may also refer to group templates defined in other groups. Model generator currently does not process correctly references to templates (in particular, chains), defined in other groups.  

We should:
1. in a group, skip references to templates (trying to expand a chain defined in another group currently throws an exception as the reference is a string and not an object).
2. include resources generated from the template into all groups that refer to the template.
Without this functionality, it is impossible to create groups that combine several external chains

**Comment by tgbugs** [comment]
The way that chains of chains should work is that the branching needs to happen inside of a housing lyph, but the details of the implementation mean that the housed lyphs must start at the border of the housing lyph. The pattern we want is closer to the dendrite/soma/axon topology, except that there isn't a soma. Having a virtual node doesn't work because we need to be able to answer queries of the form "show me all neurons with axons that branch in region x." Further cloning does not work because the semantics of a clone mean that all points are in the same physical location which would imply in this case that a wormhole has formed between the housing lyphs.

**Comment by albatros13** [comment]
![joiningChains](https://user-images.githubusercontent.com/1345692/83295785-d6ba2300-a1ef-11ea-87f4-483203c96016.png)

**Comment by tgbugs** [comment]
Here is a bit more detail, note that the upper internal lyph is really in the bottom layer I just didn't have space.
![apinat-chain-branching](https://user-images.githubusercontent.com/4299776/83300250-8bcaec00-a1ac-11ea-9750-3d406765751a.jpg)

**Comment by albatros13** [comment]
The issue remains open since we decided to connect end links of preceeding chains with start links of the following chains as opposed to their end nodes

**Comment by albatros13** [comment]
A group can inlcude references to group templates defined elsewhere. Processing of group checkboxes accounts now for nested groups. A test have been added to make sure that nested groups include all necessary resources.
