### ISSUE TITLE
how to translate json levels into a spreadsheet cell?

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#114]
`"levels": [ {}, {}, {"target": "node-branch-x"}, {} ]` How can we access this pattern via the spreadsheet? Do we try to parse cells as json? Other solutions?

**Comment by albatros13** [comment]
Proposal: since the most likely use of levels in spreadsheets is to assign nodes to levels, users do not need to be exposed to unnecessary complexity of this field. Instead, we can introduce property (exclusively for Excel) "levelTargets" that accepts format level_x: node-branch-x, i.e., 0:n1, 5:n5 would plug nodes n1 and n2 to level 0 and level 6 of the generated chain. 
(levelSources is not really needed - the only node not covered by levelTargets is a chain root, it is provided in the field "root")

**Comment by albatros13** [comment]
Added conversion and tests
