### ISSUE TITLE
force directed graph layout is broken for neuron populations?

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#145]
Not sure why this is happening, but the version running on production at https://open-physiology-viewer.surge.sh/ no longer spreads neuron populations as expected, e.g. when loading keast-bladder.json.
![apinat-viewer-no-force](https://user-images.githubusercontent.com/4299776/152073320-9d34b572-52c3-41c0-abb5-87867916b9db.png)

**Comment by tgbugs** [comment]
It seems to be ok at 1fd1ba6d2598f70a87cd3486ba316670d1bc8fc7.

**Comment by albatros13** [comment]
This effect was due to the updated rules for the resolution of conflicts for chain end positions and estimated positions of internal chain nodes: the interpolation was applied to any chain with constrained ends regardless of their origin or hosting resource visibility. Since you want to preserve force-directed layout as before, I removed constrains for chains with end nodes hosted by invisible resources. I also removed setting of 'fixed' attribute to nodes that are not on wired chain - the effect of this will be that wired chains follow exactly the wire shape while anchored chains or chains with constrained nodes will be attached only at the ends and free to move under forces.
