### ISSUE TITLE
open physiology viewer error refactoring namespace

### ISSUE THREAD

**Issue by IliasApiNATOMY10** [open-physiology/open-physiology-viewer#161]
Dear @bdebono @albatros13 @tgbugs @snegulja,
We tried to load this spreadsheet 
[1.WORKING COMMON_ApiNATOMY_template_IZ_SL (2).xlsx](https://github.com/open-physiology/open-physiology-viewer/files/8506738/1.WORKING.COMMON_ApiNATOMY_template_IZ_SL.2.xlsx)
after refactoring using the namespace for all materials. As you can see in the screenshot attached, the OpenViewer gives us errors related to the materials.
Can we please discuss this tomorrow?
Many thanks :)

![bolser](https://user-images.githubusercontent.com/97981502/163836976-a0dc0444-c61f-4e71-aaf2-fe8b5042ba45.png)

**Comment by albatros13** [comment]
This is because you tried to open the refactored model in the version of the viewer that does not support namespaces.
Try again - https://open-physiology-viewer.surge.sh/ is now running the new version. 
You will still see error messages, but they are correct error messages pointing to the missing definitions in the models.
After joining your model  with https://docs.google.com/spreadsheets/d/1Y1nPCiRTiM1A8xUQn8NwNOlsz7z32hGd6W6U_ZQOrLY/edit#gid=119835810, this is to be expected: 
![image](https://user-images.githubusercontent.com/1345692/163877722-7d1b57a1-b3e1-4c9f-abd0-f93459a27cff.png)

**Comment by albatros13** [comment]
Please fix wbkg: 
1. Add "mat-endothelial" material
2. Fix chain definitions (there must be non-empty lyphTemplate, lyphs, levels, or housingLyphs in the definition): 
"chain-female-genital" 
"chain-male-genital"  
"chain-hepatobiliary" 
"chain-pancreaticobiliary" 
"chain-male-reproductive"

**Comment by albatros13** [comment]
This issue is not reevant anymore, models have beed revised and no wbkg+ models exhibit such behavior
