### ISSUE TITLE
interalLyphsInLayers broken for wbkg models

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#199]
try to access length of a nonexistent layer because the layer spec is in another model

**Comment by albatros13** [comment]
The attempt to access length fixed. 
Most wbkg models contain errors that make it hard to judge if generator is working correctly accross namespaces.
For example, in spleen +wbkg, housingLayers should not be templates
![image](https://user-images.githubusercontent.com/1345692/192874983-70639fd6-3843-4a0c-bab3-36f768fca89b.png)

**Comment by albatros13** [comment]
Fixed by searching for layer templates not only among the explicit model lyph definitions and in the current group, but also in the map of discovered/generated resources (entitiesByID) in the namespace of the main lyph. This seems to fix the problem, the test on wbkg+Spleen ("InternalLyphsInLayers property is processed correctly") checks that lyph is placed to a generated layer of a lyph from different namespace.
