### ISSUE TITLE
neurulator

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#77]
We need to be able to identify things that are topologically equivalent to a cyst.

The test cases.

Neurons and neuron parts.
- cell
- neuron
- neuron with dendrite
- neuron with axon
- neuron with axon and dendrite
- neuron with axon branched and dendrite branched

Locations of neurons and neuron locations.
- soma location
- axon location y
- dendrite location y
- axon projection location x
- dendrite terminal location x

As an aside. An axon might fasciculate through a single nerve that has multiple segments but we wouldn't want to have to specify the housing for the nerve twice (if possible). Therefore there might be a secondary query.

**Comment by tgbugs** [comment]
Traverse the node-link graph to get maximally connected subgraphs, expand to include lyphs check that we don't have lyphs with mismatched layers connected to each other (where mismatched probably needs to be well defined based on pairwise compatibility between types, possibly also via subClassOf a common biological type or something like that). This should produce the sets of distinct connected islands that are topologically equivalent to cysts.

Similar approaches could be used for things that are topologically equivalent to bags e.g. urinary tract, lungs, etc. where we can define an end point.

**Comment by albatros13** [comment]
The suspected issue with the visualization or neurulator algorithm: the chain defined below has inverted ends and gets deceted as a cyst 
 {
            "id": "ac-img-bn2_11",
            "name": "L1 L2 DRG POS_11 axon chain from bladder nerve to bladder neck_layer2_Neuron 11 (kblad)",
            "external": ["SAO:1211023249"],
            "lyphTemplate": "229bag",
            "root": "ns141",
            "leaf": "ns143",
            "housingLayers": [3, 2],
            "housingLyphs": ["K100", "K100"]
}
When modified to 
 {
            "id": "ac-img-bn2_11",
            "name": "L1 L2 DRG POS_11 axon chain from bladder nerve to bladder neck_layer2_Neuron 11 (kblad)",
            "external": ["SAO:1211023249"],
            "lyphTemplate": "229bag",
            "root": "ns141",
            "leaf": "ns143",
           "numLevels": 2
}
the chain looks like a cyst. Hence, the inversion is not due to the bug in visualization or neuruator, but in the allocation of the chain levels alone housing lyphs. The use of the same lyph for several levels of the housing chains is not a valid modeling approach. Should lyph "K100" be a template or the purpose of this chain is to pass through the layers of the same lyph? For the latter situation, we should consider using "channels", or work out requirements for bundling chains further because the confused visualization is due to the fact that chain |--(level1]-->||--[level2)-->|  stretches along borders of layers 3 and 2 of the same lyph, turning into |--[level2 on layer 2)-->||--(level1 on layer 3]-->|, and bags look inverted.

**Comment by tgbugs** [comment]
![neurulator-cross-layer-topology](https://user-images.githubusercontent.com/4299776/118723048-c70d6300-b7e1-11eb-8f00-7b7055191bfc.png)

**Comment by tgbugs** [comment]
![apinat-multi-way-join-issue](https://user-images.githubusercontent.com/4299776/129795765-f2617d70-3f60-4c7e-bffd-4f97f89d5e4f.png)

The issue is in neuron 16. The underlying issue is that there are multiple chains that join in a way that creates a blockage.

[scaf-test-1.xlsx](https://github.com/open-physiology/open-physiology-viewer/files/7002861/scaf-test-1.xlsx)

**Comment by tgbugs** [comment]
It looks like force links are being pulled in by the nerulator and should probably be excluded.
